fix: React 19 bool prop to attr value bug
muxinc/elements pull request #1026
Opened 2024-12-06 18:45 UTC by luwes

fix https://github.com/muxinc/elements/issues/1015

2024-12-09 19:15 UTC, cjpillsbury requested changes
One callout but this general approach should be fine for simple values like booleans in React 19 (with backwards compat). 👌

2024-12-09 19:15 UTC, cjpillsbury commented on packages/mux-player-react/src/common/utils.ts
> +  defaultMuted: 'muted',
issue(blocking): This is inaccurate. `muted` needs to apply dynamically over the life of the react player instance (e.g. if someone wants to programmatically toggle `muted` via props in their react app. There is also no attribute called `defaultMuted`. The `muted` HTML attribute will map to the `defaultMuted` HTML element property. Curious why the change was made here.

2024-12-09 20:34 UTC, cjpillsbury approved these changes
🚀

2024-12-09 20:37 UTC, cjpillsbury commented on packages/mux-player-react/src/common/utils.ts
> +  defaultMuted: 'muted',
> confusing stuff.
💯

2024-12-09 20:40 UTC, merged

2024-12-10 20:28 UTC, arcataroger commented
❤️