chore: fix mux-audio and mux-video examples
muxinc/elements pull request #176
Opened 2022-04-08 20:43 UTC by dylanjha

2022-04-08 20:50 UTC, gkatsev approved these changes

2022-04-08 22:05 UTC, cjpillsbury requested changes
One minor blocking ask and a couple of non-blocking ones. Otherwise, 😎

2022-04-08 22:05 UTC, cjpillsbury commented on README_INTERNAL.md
> +1. `cd` into the `elements` directory where the origin is set to `muxinc/elements`. Don't use your forked repo, use a separate directory that is cloned from `https://github.com/muxinc/elements`.
nit (non-blocking): Copy edit -
Comma should be semicolon or a new sentence.

2022-04-08 22:05 UTC, cjpillsbury commented on README_INTERNAL.md
> +1. After approving this will kick off the deploy action which will publish all the updated packages to NPM
nit (non-blocking). Add something like this after "After approving":

> Confirm the package(s) were successfully published to npm by checking the latest version and publish time npmjs, e.g. https://www.npmjs.com/package/@mux-elements/mux-player

2022-04-11 18:00 UTC, cjpillsbury approved these changes
🏄‍♂️

2022-04-11 18:57 UTC, merged