fix(mux-uploader): Make progress, errors, completion accessible to VoiceOver
muxinc/elements pull request #264
Opened 2022-06-21 18:39 UTC by clearlyTHUYDOAN

## Description
`mux-uploader` is currently not accessible to screen readers particularly around upload states 😢 

This PR adds initial screen reader functionality for VoiceOver 🌈 

- Announces upload completion regardless if progress bar is in focus ✅ 
- Announces upload error regardless if progress bar is in focus ✅ 
- Announces current progress when progress bar is in focus ✅ 
- Ticks when progress bar is in focus and is uploading ✅ 

## Notes
- Briefly tested with ChromeVox but the browser keeps crashing. Not sure why yet.
- Normally, when contents change within a live region, it can be announced. However, it seems like when changes to contents happen within different upload events, such as progress and completion, one won't be read.
   - Currently dealing with this using a combination of `innerHTML` and `sr-only` 
 - The "Try again" element is currently a span with `role=button`. We could use the native button and style it to look like text. Though, since it was previously made a span, it was faster to just throw the right role on it for the same access. 

## Demos

**Short upload to completion**
https://user-images.githubusercontent.com/22087604/174873899-4d151e7a-5ab8-443f-99c9-b8b828403fc5.mp4

**Short upload with error**
https://user-images.githubusercontent.com/22087604/174873919-c7922e79-bfab-4798-8700-252aea977294.mp4

**Medium-sized upload to completion**
https://user-images.githubusercontent.com/22087604/174873943-92d9e25d-4159-43ba-b5db-95cc905be686.mp4

2022-06-21 21:26 UTC, clearlyTHUYDOAN commented
I checked that coverage report and it doesn't seem to be related to my direct code changes 🤔

2022-06-21 21:27 UTC, gkatsev commented
@clearlyTHUYDOAN I would ignore codecov if it goes down by less than 0.1%

2022-06-22 14:58 UTC, cjpillsbury requested changes
A few small-ish asks, but pumped about this.

2022-06-22 14:58 UTC, cjpillsbury commented on packages/mux-uploader/src/index.ts
> +    this.progressBar?.setAttribute('aria-valuenow', `${Math.floor(percent)}`);
non-blocking: why remove `aria-valuetext`?

2022-06-22 14:58 UTC, cjpillsbury commented on packages/mux-uploader/src/index.ts
> +  <span class="status-message" id="status-message" aria-live="polite"></span>
non-blocking: I think you may want to give this a [`role="status"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/status_role) to use it how you're intending? See how we've implemented [media-loading-indicator](https://github.com/muxinc/media-chrome/blob/main/src/js/media-loading-indicator.js#L65)

2022-06-22 14:58 UTC, cjpillsbury commented on packages/mux-uploader/src/index.ts
> +    this.progressBar?.focus();
😎

2022-06-22 14:58 UTC, cjpillsbury commented on packages/mux-uploader/src/index.ts
> +      // TO-DO: It seems like statusMessage cannot be updated within two different events. (TD).
This should be fine, though could be a timing issue. One way you could pin that down would be to break out the `srOnlyText.innerHTML` updates into its own function or method.

2022-06-22 19:14 UTC, clearlyTHUYDOAN commented on packages/mux-uploader/src/index.ts
> +  <div role="progressbar" aria-description="A bounded progress bar from 0 to 100" aria-valuemin="0"
I did feel like this description was too long while using a screen reader. Will change to a concise description.

2022-06-23 17:06 UTC, cjpillsbury commented on packages/mux-uploader/src/index.ts
> +    this.progressBar?.setAttribute('aria-valuenow', `${Math.floor(percent)}`);
Cool I think that's a good enough reason to prefer `aria-valuenow` for now. We can always revisit from a UX perspective which vocalizations would be preferred by users (where these tradeoffs bottom out imo, esp if the dev overhead is minimal)

2022-06-27 18:10 UTC, cjpillsbury approved these changes
😎 lgtm!

2022-06-27 18:16 UTC, merged