feat: first iteration on player redesign
muxinc/elements pull request #486
Opened 2022-10-28 18:19 UTC by luwes

- default vertical design is not included yet

2022-10-28 19:29 UTC, luwes commented on packages/mux-player/src/media-theme-mux/styles.css
> -  );
this was still a left over of when we made the time range bigger for getting more hover area.
it's now built-in Media Chrome so we can remove it here.

2022-10-28 19:30 UTC, luwes commented on packages/mux-player/src/template.ts
> +            <svg viewBox="0 0 8 8"><circle cx="4" cy="4" r="4"></circle></svg>
switched to an SVG for the dot, it's more consistent size cross-browser

2022-10-28 19:32 UTC, luwes commented on packages/mux-player/src/index.ts
> +    return this.getAttribute(PlayerAttributes.SECONDARY_COLOR) ?? 'rgb(0 0 0 / .65)';
users can still set this to an empty string to remove the secondary color

2022-10-28 19:33 UTC, luwes commented on packages/mux-player/src/media-theme-mux/styles.css
> +  background-color: var(--controls-backdrop-color, var(--controls, transparent));
the drop background color can also be set back to before if the user wants to

2022-10-28 20:59 UTC, cjpillsbury approved these changes
Good call.

2022-10-28 21:24 UTC, luwes commented on packages/mux-player/src/media-theme-mux/styles.css
> -  );
this is put back in to be able to have a better experience on mobile having a higher time range bar

2022-10-31 20:30 UTC, cjpillsbury commented
Doing some testing on the hosted app. Will add screenshots of callouts as I identify them.

2022-10-31 20:31 UTC, cjpillsbury commented
<img width="836" alt="Screen Shot 2022-10-31 at 1 29 03 PM" src="https://user-images.githubusercontent.com/2389566/199104583-30305a53-4d20-4c4c-a1c1-eda96f40b52b.png">
Live audio only could use a bit of work. 😅

2022-10-31 20:35 UTC, cjpillsbury commented
<img width="617" alt="Screen Shot 2022-10-31 at 1 33 22 PM" src="https://user-images.githubusercontent.com/2389566/199105183-84c367f9-8392-43b3-b8c4-f9bae9c3306e.png">

Live/DVR + Small shouldn't have the media-control-bar play button

2022-10-31 21:18 UTC, cjpillsbury requested changes
snapshots for reference/change requests. I'll also do an audit of the code changes.

2022-11-01 13:50 UTC, cjpillsbury commented
<img width="280" alt="Screen Shot 2022-11-01 at 6 49 29 AM" src="https://user-images.githubusercontent.com/2389566/199248991-5af11a0f-962a-4ddb-ad88-b23c492e361a.png">

Live + Extra Small has a media-time-range

2022-11-01 18:21 UTC, cjpillsbury approved these changes
😻

2022-11-01 20:31 UTC, merged