Make Lerna work in independent mode to publish pks
muxinc/elements pull request #53
Opened 2022-01-06 21:40 UTC by luwes

This will make it easier to publish packages separately, each package will have its own version.
See https://github.com/lerna/lerna#independent-mode

2022-01-07 16:35 UTC, cjpillsbury commented
@luwes This one may merit a chat. Want to make sure we aren't going to have any issues under a few circumstances, but if those are good, I'm pumped about this.

2022-01-07 22:45 UTC, luwes commented
<img width="1628" alt="Screen Shot 2022-01-07 at 4 44 05 PM" src="https://user-images.githubusercontent.com/360826/148616784-c443f478-481b-45e0-a422-cf71bb6daad5.png">

Looks like it's working well with adding a new package, `yarn install` makes the symlink.

2022-01-07 23:41 UTC, cjpillsbury commented
> Looks like it's working well with adding a new package, `yarn install` makes the symlink. Added `mux-preview` as an example.

wooohooo! I say 🚢 🇮🇹 (ship it)

2022-01-07 23:44 UTC, cjpillsbury commented
Actually one last ask before merging this. Let's update https://github.com/muxinc/elements/blob/main/README_INTERNAL.md accordingly. Otherwise, 😎

2022-01-07 23:44 UTC, cjpillsbury requested changes
Just update the publishing readme and consider it pre-approved for rebase+merging

2022-01-10 15:34 UTC, cjpillsbury requested changes
one small nit on docs.

2022-01-10 15:34 UTC, cjpillsbury commented on README_INTERNAL.md
> +1. `yarn release`
nit: 1. From the workspace root directory, run `yarn release`

2022-01-10 18:18 UTC, cjpillsbury approved these changes

2022-01-10 18:20 UTC, merged