feat: implement Mux badge
muxinc/elements pull request #988
Opened 2024-09-19 19:05 UTC by davekiss

Adds `proudly-display-mux-badge` attribute to render a linkback to Mux

2024-09-19 19:28 UTC, dylanjha commented
Such a good idea!

2025-01-07 22:43 UTC, cjpillsbury commented on packages/mux-player/REFERENCE.md
> +| `proudlyDisplayMuxBadge`              | `boolean`                                                                                                     | Display the Mux badge in the player controls.
nitpick(blocking): make sure you add  a row for the attribute as well

2025-01-07 22:44 UTC, cjpillsbury commented on examples/nextjs-with-typescript/pages/MuxPlayer.tsx
> +          proudlyDisplayMuxBadge={state.proudlyDisplayMuxBadge}
nitpick(non-blocking): consider adding a `<BooleanRenderer/>` for the attribute in our config form for easier testing

2025-01-07 22:59 UTC, cjpillsbury requested changes
looks like there's still some lingering issues here

2025-01-08 12:22 UTC, davekiss commented
@cjpillsbury turns out the `BooleanRenderer` is required for the URL query param to work

2025-01-08 17:19 UTC, cjpillsbury commented
Still not working right. Prop is properly getting passed down as an attr to the `<mux-player>` web component but not getting set on the template. I can look into this if needed.

<img width="1840" alt="Screenshot 2025-01-08 at 9 15 39 AM" src="https://github.com/user-attachments/assets/6267f656-a271-48e8-a46d-ed03b4ddcdf6" />

2025-01-10 18:27 UTC, luwes commented on packages/mux-player/src/themes/gerwig/gerwig.html
> +    proudlydisplaymuxbadge="{{proudlydisplaymuxbadge}}"
```suggestion
```

is this needed?

2025-01-10 18:35 UTC, luwes commented on packages/mux-player/src/index.ts
> +      }
```suggestion
```

this can be removed because a re-render is done below anyway

2025-01-13 18:15 UTC, luwes approved these changes
LGTM! 
make sure tests pass

2025-01-13 19:56 UTC, merged